site_name: LUX Model Documentation
nav:
  - Getting started: index.md
  - Model assumptions: assumptions.md
  - User guide:
    - Project types: user/project-types.md
    - UI tutorial: user/tutorial.md
    - Input data requirements:
      - Neighborhood: user/data/neighborhood.md
      - Businesspark: user/data/businesspark.md
      - Region: user/data/region.md
    - Interpreting results: user/results.md
    - Limitations & known issues: user/limitations.md

  - Developer guide:
    - Architecture overview: dev/architecture.md
    - Engine:
      - Overview: dev/engine/overview.md
      - Grid Nodes: dev/engine/grid_nodes.md
      - Grid Connections: dev/engine/grid_connections.md
      - Energy Cooperatives: dev/engine/energy_coops.md
      - Energy Assets: dev/engine/energy_assets.md
      - Consistency Checks: dev/engine/consistency_checks.md
      - Energy Management Systems: dev/engine/energy_management_systems.md
      - Option Lists: dev/engine/option_lists.md
      - Energy Carriers: dev/engine/energy_carriers.md
      - Energy Model: dev/engine/energy_model.md
      - Energy Data: dev/engine/energy_data.md
      - Data Structures:
        - Overview: dev/engine/data_structures/data_structures.md
        - Time Series: dev/engine/data_structures/time_series.md
        - Accumulators: dev/engine/data_structures/accumulators.md
        - Accumulator Maps: dev/engine/data_structures/accumulator_maps.md
        - Value Maps: dev/engine/data_structures/value_maps.md
        - Flows Maps: dev/engine/data_structures/flows_maps.md
        - DataSet Maps: dev/engine/data_structures/dataset_maps.md
        - Profile Pointers: dev/engine/data_structures/profile_pointers.md
        - Profile Forecasters: dev/engine/data_structures/profile_forecasters.md
    - Loader:
      - Overview: dev/loader/overview.md
      - Lombok: dev/loader/lombok/lombok.md
      - Data Generic:
        - Overview: loader/data_Generic/data_Generic.md
        - Domestic hot water tapping profiles: loader/data_Generic/DHW_profiles.md
    - Interface:
      - Overview: dev/interface/overview.md
    - ResultsUI:
      - Overview: dev/resultsUI/overview.md

theme: readthedocs
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra