FROM docker.io/library/python:3.14.5 AS builder

WORKDIR /app

RUN pip install mkdocs pymdown-extensions

# --parents is unsupported by older Podman on GitHub Actions.
#COPY --parents mkdocs.yml docs /app/
COPY mkdocs.yml /app/
COPY docs/ /app/docs/
RUN mkdocs build

FROM lipanski/docker-static-website:latest

COPY --from=builder /app/site .

CMD ["/busybox-httpd", "-f", "-v", "-p", "3000"]
